### ISSUE TITLE
Example for version 2.11.** is wrong

### ISSUE THREAD

**Issue by diclofoss** [JRakNet/JRakNet#105]
Hello!
Your example meets 2.10.7 version

**Comment by whirvis** [comment]
What do you mean by that? Does the code not compile? I would also like to know which example code you're referring to :)

**Comment by diclofoss** [comment]
Server example. Code is not compled.
RakNetClientSession - missed

**Comment by whirvis** [comment]
Could you elaborate on that? I'm not sure what that means that I missed ``RakNetClientSession``

**Comment by diclofoss** [comment]
for example in 2.10 interface:

public interface RakNetServerListener {

has public void onClientConnect(RakNetClientSession session) {

in 2.11

	public default void onConnect(RakNetServer server, InetSocketAddress address, ConnectionType connectionType) {

**Comment by whirvis** [comment]
Oh! That's intentional. You must be thinking of the ``onLogin`` method, which is different from the ``onConnect`` method. ``onConnect`` is simply when a client has connected to the server, but has not yet logged in and created an official session. Also, there are no longer session, they are called peers. In this case, ``RakNetClientSession`` would be ``RakNetClientPeer``.

If you are ever confused to what a method does, please read the documentation provided alongside it. If it still confuses you, feel free to make another issue with the Question tag! :)

**Comment by diclofoss** [comment]
I have dealed with your code. NP. The example is not compatible with 2.11.** version. This is bug

**Comment by whirvis** [comment]
Ah, you meant in the README.md file! My bad. I thought you meant somewhere else, I'll fix this now :)
