### ISSUE TITLE
MCPE 1.1 not connecting

### ISSUE THREAD

**Issue by DaMatrix** [JRakNet/JRakNet#37]
What the title says. With PE 1.1 neither `onClientConnect`, `onClientDisconnect` or `handleMessage` are being called, and the client doesn't show the server in the server list.

**Comment by whirvis** [comment]
~~This is not a bug, you are simply using the server wrong. Could I see all your server implementation code?~~
If you are connecting to the server from a Windows 10 edition instance on the same machine on the default port (19132) the game simply will not be able to connect due to unknown reasons (This is a Mojang issue, not a JRakNet issue). To fix this, set the port to anything but 19132 or use a different device.

**Comment by DaMatrix** [comment]
i'm using 19133

**Comment by DaMatrix** [comment]
https://github.com/Team-Pepsi/PepsiProxy/blob/master/pepsiproxy_main/src/main/java/net/daporkchop/pepsiproxy/PepsiProxy.java#L31
