### ISSUE TITLE
java.lang.IndexOutOfBoundsException: ... UnpooledUnsafeHeapByteBuf on server, and didn't call handleMessage()

### ISSUE THREAD

**Issue by haxpor** [JRakNet/JRakNet#41]
I've tried to properly sending message from client to server for quite long time without success.

I did read document on [Raknet](http://www.raknet.net/raknet/manual/), and saw a few sample code here of JRakNet in issues section as I cannot find it anywhere. But still I cannot make it through. I believe it might due to I didn't do it properly and correctly in the way of Raknet.

From testing, as soon as client connected and then sent message, server has the following error (but not crash)

```
java.lang.IndexOutOfBoundsException: readerIndex(19) + length(1) exceeds writerIndex(19): UnpooledUnsafeHeapByteBuf(ridx: 19, widx: 19, cap: 19)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1413)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
	at net.marfgamer.jraknet.Packet.readTriadLE(Packet.java:239)
	at net.marfgamer.jraknet.protocol.message.EncapsulatedPacket.decode(EncapsulatedPacket.java:107)
	at net.marfgamer.jraknet.protocol.message.CustomPacket.decode(CustomPacket.java:76)
	at net.marfgamer.jraknet.server.RakNetServer.handleMessage(RakNetServer.java:607)
	at net.marfgamer.jraknet.server.RakNetServerHandler.channelRead(RakNetServerHandler.java:128)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1319)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:904)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:805)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:748)
```

it didn't receive any message, it didn't call `handleMessage()`. Right after that client will be timeout.

I have the following quick testing code for both server and client.
Here is for server code (in Kotlin)

```kotlin
import net.marfgamer.jraknet.server.RakNetServer
import net.marfgamer.jraknet.server.RakNetServerListener
import net.marfgamer.jraknet.session.RakNetClientSession
import net.marfgamer.jraknet.RakNetPacket

fun main(args: Array<String>) {
	val server = RakNetServer(5670, 10)

	server.listener = object: RakNetServerListener {
		override fun onClientConnect(session: RakNetClientSession) {
			println("Client connected from ${session.address}")
		}

		override fun onClientDisconnect(session: RakNetClientSession, reason: String) {
			println("Client disconnected: ${session.address}")
		}

		override fun handleMessage(session: RakNetClientSession, packet: RakNetPacket, channel: Int) {
			println("Got message from ${session.address}, packet id: ${packet.id}")
		}

		override fun onServerStart() {
			println("Server started")
		}
	}

	server.start()
}
```

and here for client side

```kotlin
import java.net.InetSocketAddress
import net.marfgamer.jraknet.client.RakNetClient
import net.marfgamer.jraknet.client.RakNetClientListener
import net.marfgamer.jraknet.session.RakNetServerSession
import net.marfgamer.jraknet.RakNetPacket
import net.marfgamer.jraknet.protocol.Reliability
import net.marfgamer.jraknet.protocol.MessageIdentifier
import net.marfgamer.jraknet.protocol.message.acknowledge.Record
import net.marfgamer.jraknet.protocol.message.CustomPacket

class Client {
	
	interface Listener {
		fun onClient_Connect(client: Client)
		fun onClient_Disconnect(client: Client)
	}

	val SERVER_ADDRESS: String = "xxx.xxx.xxx.xxx"
	val SERVER_PORT: Int = 5070

	val client = RakNetClient()
	var listener: Listener? = null

	init {
			val that = this

			client.listener = object: RakNetClientListener {
			override fun onConnect(session: RakNetServerSession) {
				println("Successfully connected to server with address ${session.address}")

				that.listener?.onClient_Connect(that)
			}

			override fun onDisconnect(session: RakNetServerSession, reason: String) {
				println("Successfully disconnected from server with address ${session.address}")

				that.listener?.onClient_Disconnect(that)

				client.shutdown()
			}

			override fun onAcknowledge(session: RakNetServerSession, record: Record) {
				println("Acked ${record.index}:${record.endIndex}")
			}

			override fun onNotAcknowledge(session: RakNetServerSession, record: Record) {
				println("Not ack ${record.index}:${record.endIndex}")
			}

			override fun handleMessage(session: RakNetServerSession, packet: RakNetPacket, channel: Int) {
				println("Received ${packet.readString()} on channel: $channel")
			}

			override fun onHandlerException(address: InetSocketAddress, throwable: Throwable) {
				println("handled exception")
				throwable.printStackTrace();
			}

			override fun onThreadException(throwable: Throwable) {
				println("handled thread exception")
				throwable.printStackTrace();
			}
		}
	}

	fun connectThreaded() {
		client.connectThreaded(SERVER_ADDRESS, SERVER_PORT)
	}

	fun sendMessage(message: String) {
		val packet = RakNetPacket(MessageIdentifier.ID_USER_PACKET_ENUM.toInt())
		packet.write((message).toByteArray())
		client.sendMessage(Reliability.RELIABLE_SEQUENCED_WITH_ACK_RECEIPT, 0, packet)
	}
}

class Consumer: Client.Listener {
	val client = Client()
	
	init {
		client.listener = this
		client.connectThreaded()
	}

	override fun onClient_Connect(client: Client) {
		client.sendMessage("Hello")
		println("sent message")
	}

	override fun onClient_Disconnect(client: Client) {
	}
}

fun main(args: Array<String>)  {
	Consumer()
}
```

Note for client side, I started the client with `connectThreaded()` to avoid blocking in calling thread.

What did I do wrong here? Please kindly point me out to the proper and correct way to send message from client to server. Thanks!

**PS**: Not for minecraft server, just normal server/client setup.

**Comment by haxpor** [comment]
Problem solved.

The catch is that I need to use `Reliability` constants that not include `ACK` and `RECEIPT` i.e. `UNRELIABLE_SEQUENCED_WITH_ACK_RECEIPT`, `RELIABLE_ORDERED_WITH_ACK_RECEIPT` etc. But I still wonder why?

I modified the code and had working sample now, for anyone interested you can see [here](https://gist.github.com/haxpor/99be7dd94ee4b6b59ed2f497be94e07d).

**Comment by whirvis** [comment]
Why were you reading the documents for RakNet? Those are outdated and no longer kept up with, you need to read them for JRakNet. But this is interesting, I will look into it to make sure you weren't actually causing the glitch before closing the issue. :)

**Comment by whirvis** [comment]
It seems that this is a JRakNet glitch, I will look into this.

**Comment by whirvis** [comment]
@haxpor Good news, I found a solution! Indeed, it was not your fault but rather a glitch in JRakNet. While I have fixed said bug, I do regret saying that I have not yet implemented actual support for _WITH_ACK_RECEIPT reliabilites as I am not sure how to. I will implement support for it as soon as possible, thank you for reporting this bug!

**Comment by haxpor** [comment]
Good to hear. No problem at the meantime I use those without WITH_ACK_RECEIPT. But although without such ack, if I send it with RELIABLE, I have no need and it's alright to operate with _WITH_ACK_RECEIPT if I don't do anything after another end ACK back?

On a side, could you please point me out to JRakNet documentation? I can find only simple demo code that client/server connects with each other but not send/receive any packets. I might miss something. Thank you Marf!

**Comment by whirvis** [comment]
No problem :) At the moment, I have no server to post it so I use HTML Preview, the link is in the top of the ReadMe where it says "You can also read the JavaDocs" right above the versions of RakNet supported.

About the reliabilites that end in _WITH_ACK_RECEIPT, I believe those are supposed to be used to let a server know whether or not a packet was sent or lost but I'm not sure how to implement that functionality, however this should not cause a glitch when sending packets. The glitch was being caused due to incorrect bit shifting causing ID's like -1 to be returned when being decoded, resulting in an ArrayIndexOutOfBoundsException due to the length of the packet being incorrectly decoding or a NullPointerException due to the ID not being used by any of the reliabilites.

I'm not sure what you're asking about the RELIABLE reliability, are you asking if it's safe to not use _WITH_ACK_RECEIPT and not check if the packet was sent? If that is the case, then yes. Here, I will list out how each Reliability behaves for packets and I will also include these definitions in the documentation later before release :)

- Reliabities
  - UNRELIABLE: The packet will be sent, however there is no guarantee it will even come in.
  - UNRELIABLE_SEQUENCED: Same as UNRELIABLE, however it will not be handled if a newer packet with this reliability on the channel has already been received.
  - RELIABLE: Guarantees the packet will be sent at some point.
  - RELIABLE_SEQUENCED: Same as RELIABLE, however it will not be handled if a newer packet with this reliability on the channel has already been received.
  - RELIABLE_ORDERED: Same as RELIABLE, however it will not be handled until every packet in the channel has been sent and they can be handled in the order they were sent. This is why there is no UNRELIABLE_ORDERED, as if it were UNRELIABLE the whole channel would stop working if even one of the packets got lost and the slot could not be filled.
  - UNRELIABLE_WITH_ACK_RECEIPT: Same as UNRELIABLE, however I am unsure how ACK Receipts work, so I am unable to say what the _WITH_ACK_RECEIPT is responsible for.
  - RELIABLE_WITH_ACK_RECEIPT: Same as RELIABLE, however I am unsure of how ACK receipts work, so I am unable to say what the _WITH_ACK_RECEIPT is responsible for.
  - RELIABLE_ORDERED_WITH_ACK_RECEIPT: Same as RELIABLE, however I am unsure of how ACK receipts work, so I am unable to say what the _WITH_ACK_RECEIPT is responsible for.

And one last thing, the reason you see no packets coming in with the server or client in the example code is because in said example code no packets are being sent. All packets with ID's below the user packet enum are handled internally by the server and client.

So since I am unsure of how to do implement the _WITH_ACK_RECEIPT functionality, I would suggest you stay away from those 3 reliabilites. :)

**Comment by haxpor** [comment]
Thank you for detailed answer for how this stuff works! Also I did indeed miss your example code there in Javadocs although I clearly saw the link at the top of README, I thought it's just API Doc only for reference which normally doesn't include example code. But after I clearly look at it, I saw `example` package then it leads me to browsing through JRakNet's codebase locally. Thanks for that in pointing me out in the right direction.

Also clearer for me now for Reliabilities. 👍

**Comment by haxpor** [comment]
@MarfGamer Just to be clear, is 8f6f134 fixed this issue?

**Comment by whirvis** [comment]
@haxpor It is fixed but the version with the fix has not yet been released. I will release it as soon as possible. However, the actual _WITH_ACK_RELIABILITY functionality has not yet been implemented. I will make a TODO issue now.

**Comment by whirvis** [comment]
@haxpor Good news! I have implemented the _WITH_ACK_RECEIPT functionality that originally caused this glitch :)

An example of how to use it can be found in the [RakNetServerSession](https://github.com/JRakNet/JRakNet/blob/master/src/main/java/net/marfgamer/jraknet/session/RakNetServerSession.java#L55) class. In order to use it properly, cache the EncapsulatedPacket that was returned when you sent the packet using the sendMessage() method. Next, in the onAcknowledge() method, compare the record with the record found in the cached Encapsulated packet (the variable name for it is ackRecord). If you are sending an unreliable packet that requires an ack receipt, there is also the possibility that it will be lost. If you want to see if it's lost, just do the same but change the method name from onAcknowledge() to onNotAcknowledge() which has all of the same parameters and behavior with the exception that it's letting you that a packet was lost instead of received.

**Comment by haxpor** [comment]
Thank you for great work @MarfGamer . Noted. I'll try it out.
