### ISSUE TITLE
Extremely high CPU usage

### ISSUE THREAD

**Issue by DaMatrix** [JRakNet/JRakNet#61]
Server startThreaded seems to take up the whole core it's running on, not sure if this is intended but not good regardless.

**Comment by DaMatrix** [comment]
It seems start() does it too, and neither of them seem to be capable of processing packets. (event is never called)

**Comment by whirvis** [comment]
What do you mean "not capable of processing packets"?

**Comment by DaMatrix** [comment]
As in "packets sent to the server are seemingly not recieved or processed".  I've even tried with the examples, CPU instantly goes to 100%.

**Comment by DaMatrix** [comment]
I'm just using basic Netty now, it works for my needs (just need to send some bytes)

**Comment by whirvis** [comment]
I will look into the CPU usage issue. I'm not sure what's causing this at all. First, could you tell me what program you are using to see the CPU usage? Second, could I see the code you were using to have the server and client communicate?

**Comment by DaMatrix** [comment]
[Server code](https://bitbucket.org/TeamPepsi/pepsimodserver/src/ce2516d7aad6faff49614377feac654cf8dd2277/src/main/java/team/pepsi/pepsimod/server/Server.java?at=master&fileviewer=file-view-default)

I was literally just using the code in the example in the README for testing (with an extra packet sent with RELIABLE_ORDERED), and a debug message on the server showed that the packet was never recieved and the client never disconnected.  However a debug message on the client showed that the data was in fact being sent.

**Comment by MarfGamer** [comment]
Did you have logging enabled on the server? If you did, what level did you set it to?

**Comment by whirvis** [comment]
@DaMatrix I think I've found a solution. I've been researching and I found that when using while(true), depending on the implementation on the OS for Java it will most likely use a TON of CPU because the OS doesn't give the CPU any time to process anything else and thus causes a huge slowdown. I've found that simply using `Thread.sleep(0, 1)` is enough to to bring it down from a consistent 12.50%+ on my machine down to <0.35% on the server and down to less than 0.05% for the client.

~~For the data not being sent on the client I'm not sure what to tell you. I can't find anything really wrong in the code you sent me. By any chance, were you using Windows 10 edition on the same device the server was running on? Because if so, there's nothing I can do about that. You will have to use another device that runs Minecraft with the Bedrock Engine (Which is currently Windows 10, XBOX One, Android, iOS, and soon Nintendo Switch)~~

EDIT: I think I know what you're talking about now. It seems that for whatever reason the client stops updating the session which prevents data from being sent and also seems to block the thread. I will look into this issue.

EDIT TWO: The issue seems to be coming from a rogue `synchronized` block found in the sendMessage() and update() methods which is causing the JVM to lock up.

**Comment by whirvis** [comment]
This issue has been fixed in v2.8.0. @DaMatrix, could you get back to me and tell me if it is working any better at all now?

**Comment by DaMatrix** [comment]
yup, seems to be working fine. thanks!

**Comment by whirvis** [comment]
No problem! Thank you for reporting the problem to me and working with me to help get it fixed :)

**Comment by whirvis** [comment]
@DaMatrix Even though this issue has been closed a few other issues have just been fixed so I wanted to let you know that v2.8.1 has been released just in case you were using 2.8.0.
