### ISSUE TITLE
Unable to connect to world.

### ISSUE THREAD

**Issue by s5bug** [JRakNet/JRakNet#62]
![Screenshot](https://user-images.githubusercontent.com/7751296/31062611-badf3e34-a6e0-11e7-98bf-29f94011089b.png)

I setup my server on port `19137`:

```
package com.tsunderebug.cpe

import net.marfgamer.jraknet.identifier.{Identifier, MCPEIdentifier}
import net.marfgamer.jraknet.server.{RakNetServer, RakNetServerListener}
import net.marfgamer.jraknet.session.RakNetClientSession

import scala.util.Random

object Main {

  var onlineCount = 0
  val uid: Long = new Random().nextLong()

  def main(args: Array[String]): Unit = {
    val server = new RakNetServer(19137, 10, mcpeIdentifier)
    server.setListener(new RakNetServerListener {

      override def onClientConnect(session: RakNetClientSession): Unit = {
        onlineCount += 1
        server.setIdentifier(mcpeIdentifier)
        println("cl")
      }

      override def onClientDisconnect(session: RakNetClientSession, reason: String): Unit = {
        onlineCount -= 1
        server.setIdentifier(mcpeIdentifier)
      }

    })

    server.start()
  }

  def mcpeIdentifier: Identifier = new MCPEIdentifier("Memeoculos", 101, "1.0.3", onlineCount, 10, uid, "Meme World", "Creative")

}
```

but when I go to the Friends tab, it doesn't show up, and when I go to Servers and add `127.0.0.1`, `19137`, it doesn't get info from it and when trying to join shows that error.

**Comment by whirvis** [comment]
First off, JRakNet is not an MCPE server, it is only a protocol implementation of the underlying networking library. Second, the reason your server isn't showing up is due to a bug on the Windows 10 edition where it is unable to connect to servers on the same machine. I am not sure what causes this, but it is not related to JRakNet. To see what I'm talking about, launch the server you created and open Minecraft on another device (XBOX One, Android, iOS, another Windows 10 computer than the one the server is running on, etc.)

If you look at the README.md file, it _clearly_ says at the beginning of the document that JRakNet is a protocol implementation of **RakNet**, however it was made so people using Java could easily get things up and running to create the server and start implementing MCPE's protocol from there.

Edit: You don't need to track the player count on line 25, JRakNet does that for you. All you need to do is call server.getSessionCount(). Did you read any of the documentation or look at any of the examples or test code?

**Comment by s5bug** [comment]
The example code doesn't show much and the documentation is minimal.

**Comment by whirvis** [comment]
Have you looked at all in the src/main/test or src/main/test/example folders at all (not the README examples)? If so, I apologize that the examples and test code do not provide enough information. Is there anything you would like me to add in terms of example code?

Also, by documentation, do you mean JavaDocs?

**Comment by s5bug** [comment]
I'd like it to be explained that this is not a full fledged MCPE server and a brief guide on how to make one/link to vgwiki's article on the MCPE RakNet protocol. And the JDoc is very simple, often lacking an example.

I would help but I have a lot on my plate as well :sweat_smile:

**Comment by MrPowerGamerBR** [comment]
vgwiki's MCPE documentation is severly outdated

**Comment by whirvis** [comment]
@TsundereBug Like I said before, the README file clearly states that this is for multiplayer software using the RakNet protocol (However, it was originally made for Minecraft so it is optimized for it). On top of that, wikiVG is outdated by over 3 years and should not even be touched. At the moment, we don't even know what the protocol is for 1.2 (Protocol 137) because Microsoft is playing favorites and only handing out the protocol to their partners.

However I will look into the JavaDoc issue and will add more examples as I agree that there are not many examples in the documentation.

**Comment by DefinitlyEvil** [comment]
Hey @MarfGamer :
First of all, thanks for your awesome work. I am using your library in my DragonProxy project, I updated to latest version even tried snapshots from jitpack but I can't get a server ping and unable to connect at all. Server handler seems useless because it didn't call the method which I added print-out stuffs. 

```java
   public RaknetInterface(DragonProxy proxy, String ip, int port) {
        this.proxy = proxy;
        rakServer = new RakNetServer(port, Integer.MAX_VALUE);
        rakServer.addListener(this);
        sessions = this.proxy.getSessionRegister();
        rakServer.startThreaded();
    }

    public void setBroadcastName(String serverName, int players, int maxPlayers) {
        rakServer.setIdentifier(new MinecraftIdentifier(serverName, Versioning.MINECRAFT_PE_PROTOCOL, Versioning.MINECRAFT_PE_VERSION, players, maxPlayers, new Random().nextLong(), "DragonProxy", "Survival"));
    }
```
