### ISSUE TITLE
Minecraft: Windows 10 edition fails to connect to the server

### ISSUE THREAD

**Issue by imjack** [JRakNet/JRakNet#9]
I'm running your server example code on Windows 10 and trying to connect to the server using the Minecraft: Windows 10 edition. Whenever I attempt to connect to the server from this version on my machine [this error is thrown](https://gist.github.com/imjack/c797821a30166ca08871b61ac9d5b2ec). The server is running on the default Minecraft PC port (25565). Also, connecting to the server works fine on Minecraft: Pocket Edition, it only crashes when using Minecraft: Windows 10 Edition.

**Comment by whirvis** [comment]
The error is coming from 0x13 (NewIncomingConnectionPacket) failing to read an address properly, I will look into this issue.

**Update:** The reason for the failure is that the address type (the first byte) is returning 254, and during the read the Packet class checks if it is IPv4. If it is, it reads it and returns it as an InetSocketAddres. If it is anything else it just reads that amount of bytes and returns null. So when the version returns 254 and there are less than 270 bytes (Extra 16 bytes for the server and client timestamp) the packet runs out of data to read. This seems to be a glitch on Mojang's side, as this does not happen on mobile. For now I will leave the issue open as there is also the possibility that there is a purposeful difference in the protocol between the two versions for some reason.

**Update 2:** [Sent a bug report to Mojang](https://bugs.mojang.com/browse/MCPE-18583)

**Update 3:** Fixed in v2.2.4
